### ISSUE TITLE
To-do for v3.0

### ISSUE THREAD

**Issue by shawna-p** [shawna-p/mysterious-messenger#14]
**General To-Do**
- [ ] Add links to script error screens to relevant wiki pages
- [x] Clean up comments & check for comment language consistency
- [x] Update reset persistent function for new persistents
- [x] Create example StoryCall (attached)
- [x] Create example StoryCall (standalone)
- [x] Create example StoryMode (standalone)
- [x] Create example Good/Normal end parties
- [x] Rewrite classes to TimelineItem (+ CDSs)
- [x] Ensure paraphrase mode is set properly for Tutorial Day
- [x] Update blurry profile pictures (where possible)
- [x] Ensure animated backgrounds hide when switching to VN (since on separate layer)
- [x] Hide timed menus/continuous menus when backing out of chatroom/at end of chatroom
- [x] Remove non-webp images
- [x] Save after buyahead/buyback on timeline screens

**Testing**
- [x] Test ending starter story on phone call/chatroom/VN
- [x] Test if attached parties can branch
- [x] Test TimelineItem integration
- [x] Test standalone StoryMode
- [x] Test standalone StoryCall (and expiry)
- [x] Test custom ending screen functionality
- [x] Test custom fonts and bubbles for `msg` CDS
- [x] Test custom specBubble functions
- [x] Test compose text realtime
- [x] Test compose text asynchronous
- [x] Test compose text next_item
- [x] Test compose text random
- [x] Test compose text deliver_at a specific time
- [x] Test MC profile picture callback
- [x] Test `scene` and `show` with chatroom modifications
- [x] Test `clear chat` and `clear chat participants`
- [x] Test timed menus from the History
- [ ] Test continuous menus from the History
- [x] Test timed/continuous menus with pauses
- [x] Test timed/continuous menu replay in-game
- [x] Test timed/continuous menus which are "empty"

**Bugs**
- [x] Unlock 24h seems to be unlocking one item after it should (e.g. unlocking 9:15pm chatroom when activated at 8:30pm)
- [x] Skip intro doesn't work when you're about to answer something (and by extension, end chatroom test button); check if it works in the middle of a timed/continuous menu
- [x] Timed menus continue to animate when back button is pressed

**Wiki Pages:**
- [x] `add_to_album`, `hide_album` in Gallery 
- [x] `play music` and `play sound` updates
- [x] `variables_editable` -> Add references to existing pages
- [x] `StoryMode`
- [x] `StoryCall`
- [x] `_branch` for parties
- [x] Mention guestbook HG reward in emails
- [x] Example route definition & explanation
- [x] `invite guest` CDS
- [x] `award heart` and `break heart` CDS
- [x] `$ ending = 'bg bad end'` aka defining your own ending screen image
- [x] `msg` CDS for dialogue writing
- [x] Custom `specBubble`
- [x] `text backlog` CDS
- [x] `compose text` CDS
- [x] `enter` and `exit chatroom` CDSs
- [x] `was_expired` for conditionals based on whether an item was expired
- [x] `-b` and `-thumb` for album
- [x] Bonus profile pictures
- [x] MC profile picture callback
- [x] Paraphrase mode
- [x] `scene` and `show` used for chatroom effects (hack, banner, background)
- [x] `clear chat` CDS and `clear chat participants`
- [x] Customizing the History screen route backgrounds
- [x] `timed menu`
- [ ] `continuous menu`
- [x] `show_empty_menus` variable

**To update:**
- [x] TimelineItem vs ChatHistory/VNMode
- [x] CDS replacements
- [x] `.webp` conversion
- [x] Creating a new character checklist
- [x] Filename substitution for albums
- [x] Keyboard shortcuts
- [x] Renamed `autoanswer timed menus`
- [x] Testing mode additions (instantly ending chatrooms, show all history items, profile pictures)
